# Generated by Django 4.2.6 on 2023-10-23 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="content",
            old_name="course_id",
            new_name="course",
        ),
    ]
