# Generated by Django 4.2.6 on 2023-10-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("students_courses", "0001_initial"),
        ("courses", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="my_courses",
            field=models.ManyToManyField(
                related_name="students",
                through="students_courses.StudentCourse",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="account_permissions", to="auth.permission"
            ),
        ),
    ]
