# Generated by Django 4.2.6 on 2023-10-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students_courses", "0001_initial"),
        ("courses", "0002_rename_instructor_id_course_instructor"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="my_courses",
            field=models.ManyToManyField(
                related_name="students",
                through="students_courses.StudentCourse",
                to="courses.course",
            ),
        ),
    ]
