# Generated by Django 4.2.6 on 2023-10-23 12:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="instructor_id",
            new_name="instructor",
        ),
    ]
